language: android

sudo: required
sudo: false

jdk: oraclejdk7

env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-21.1.1
    - android-17
    - sys-img-armeabi-v7a-android-17
    - extra-android-support

before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - chmod +x ./gradlew
  - chmod +x ./ci/wait_for_emulator.sh
  - ./ci/wait_for_emulator.sh
  - adb shell input keyevent 82 &
